services:
  mongodb:
    image: mongo:4.4.29
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: turbo
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    command: "mongod --replSet rs0"

  mongodb-init-job:
    image: mongo:4.4.29
    container_name: mongodb-init-job
    command: >
      bash -c "
      sleep 10;
      mongo --host mongodb:27017 --eval 'rs.initiate()';
      mongo --host mongodb:27017 --authenticationDatabase admin --eval '
        db.getSiblingDB(\"admin\").createUser({
          user: \"admin\",
          pwd: \"admin\",
          roles: [{ role: \"root\", db: \"admin\" }]
        });
      '"
    depends_on:
      - mongodb

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/turbo?authSource=admin
      - DAPR_PUBSUB_NAME=pubsub
    depends_on:
      - mongodb
      # - dapr
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"

  # dapr:
  #   image: daprio/daprd:latest
  #   container_name: dapr
  #   command: [
  #     "./daprd",
  #     "-app-id", "backend",
  #     "-app-port", "3000",
  #     "-components-path", "/components"
  #   ]
  #   volumes:
  #     - ./dapr/components:/components
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "./bitnami:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "./bitnami:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=turbo_turbo:1:1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  gravity:
    build:
      context: ./gravity
      dockerfile: Dockerfile
    container_name: gravity
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./gravity/config.toml:/app/config.toml
    depends_on:
      - mongodb
      # - dapr
    restart: unless-stopped

volumes:
  mongo-data: