version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: turbo
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
      - ./mongodb/initdb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/turbo?authSource=admin
      - DAPR_PUBSUB_NAME=pubsub
    depends_on:
      - mongodb
      - dapr
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  dapr:
    image: daprio/daprd:latest
    container_name: dapr
    command: [
      "./daprd",
      "-app-id", "backend",
      "-app-port", "3000",
      "-components-path", "/components"
    ]
    volumes:
      - ./dapr/components:/components
    depends_on:
      - backend
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  gravity:
    image: martenseemann/gravity:latest
    container_name: gravity
    volumes:
      - ./gravity/config.yaml:/etc/gravity/config.yaml
    depends_on:
      - mongodb
      - dapr

volumes:
  mongo-data: