name = "mongo2kafka"

[input]
type = "mongo"
mode = "stream"

[input.config.source]
host = "mongodb"
port = 27017
username = "admin"
password = "admin"
auth-db = "admin"

[output]
type = "async-kafka"

[output.config.kafka-global-config]
broker-addrs = ["kafka:9092"]

[[output.config.routes]]
match-schema = "turbo"
match-table = "turbo"
dml-topic = "turbo_turbo"

[scheduler]
type = "batch-table-scheduler"
[scheduler.config]
nr-worker = 1
batch-size = 100
queue-size = 1024
sliding-window-size = 1024